name: Lint

on:
  push:
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install npm dependencies
      run: yarn install
    - name: Run Linter
      run: yarn lint